alias: Set oscillating & angle
description: ''
trigger:
    - platform: state
      entity_id:
          - input_select.dyson_oscillating
condition: []
action:
    - if:
          - condition: not
            conditions:
                - condition: state
                  entity_id: input_select.dyson_oscillating
                  state: '0'
      then:
          - service: dyson_local.set_angle
            data:
                entity_id: fan.bedroom
                angle_high: >-
                    {{ int(states('input_number.dyson_angle')) +
                    ((int(states('input_select.dyson_oscillating')) / 2) | round(0)) }}
                angle_low: >-
                    {{ int(states('input_number.dyson_angle')) -
                    ((int(states('input_select.dyson_oscillating')) / 2) | round(0)) }}
      else:
          - service: dyson_local.set_angle
            data:
                entity_id: fan.bedroom
                angle_high: "{{ int(states('input_number.dyson_angle')) }}"
                angle_low: "{{ int(states('input_number.dyson_angle')) }}"
mode: single
